name: Build and dry run

on:
  push:
    branches: [ main, cleanup ]
  pull_request:
    branches: [ main, cleanup ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4


      - name: Install HDF5 and MPI
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-dev libhdf5-openmpi-dev openmpi-bin

      - name: Compile matrix
        run: ./tests/build_matrix.sh

      - name: Run executable (dry-run mode)
        run: |
          make SYSTYPE=Ubuntu DEFINES=-DDRY_RUN
          ./ProteusGPU
